//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopDAL.Model
{
    using System;
    using System.Collections.Generic;
	using ShopDALModel.BaseModel;

	public partial class Brand : HashValues
    {
		
    }
}
