//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ShopDALModel.BaseModel
{
    using System;
    using System.Collections.Generic;
	
    public abstract class Product : Entity, IProductModel
    {
        public int SizeId { get; set; }
        public int BrandId { get; set; }
        public int DestinationId { get; set; }
        public int ColourId { get; set; }
		[MaxLength(10), MinLength(2)] 
        public string Code { get; set; }
		[MaxLength(255), MinLength(0)] 
		public string Name { get; set; }
        public double Price { get; set; }
	    public int CategoryId { get; set; }

    }
}
